---
label: default-article
hide_body: false
fields:
- type: text
  name: title
  label: title
  description: Enter the title of the article here.
- type: text
  name: slug
  label: slug
  description: This is what the url in the address bar will look like (ie. https://www.chinderzytig.ch/<strong>the-slug-is-here</strong>).
    You don't need to fill this out as it will automatically take the title.
  hidden: false
- type: text
  name: description
  label: description
  description: A one sentence description regarding what the article is about. This
    is use for SEO purposes (ie. when an article is shared or displayed in web search
    results).
- type: datetime
  name: date
  label: date
- type: text
  name: author
  description: Author of the article
  label: Article author
- type: file
  name: hero_img
  label: hero_img
  description: The main image for the article. Upload the image to Cloudinary via
    the "Upload" button in the top-right hand corner of the image library
- type: text
  name: img_description
  label: img_description
  description: Short description of the image (ie. "Refugees standing in food line").
    Used for blind persons using screen readers and used in lieu when an image can't
    be loaded on the screen.
- type: text
  name: img_photographer
  label: img_photographer
  description: Name of the photographer who took the photo.
- type: textarea
  name: img_src
  label: img_src
  description: Enter the URL of where you got the photo from.
- name: cc_licence
  type: text
  config:
    required: false
  label: cc_licence
  description: If Creative Commons attribution is required, enter the licence type
    here (ie. CC BY-SA)
- name: cc_src
  type: text
  config:
    required: false
  label: cc_src
  description: 'If Creative Commons attribution is required, enter the link to the
    webpage of the specific Creative Commons licence being used. '
- type: list
  name: kategorien
  description: 'Add any categories to the article. The categories are: <strong>Nordamerika</strong>,
    <strong>Südamerika</strong>, <strong>Europa</strong>, <strong>Afrika</strong>,
    <strong>Asien</strong>, <strong>Australien</strong>, <strong>Antarktis</strong>,
    <strong>Gesellschaft</strong>, <strong>Gesundheit</strong>, <strong>Medien</strong>,
    <strong>Natur/Umwelt</strong>, <strong>Politik</strong>, <strong>Weltraum/Universum</strong>,
    <strong>Welt</strong>'
  config:
    use_select: false
  label: kategorien
- type: list
  name: markierungen
  label: markierungen
  description: Add any tags to the article. Tags can be anything that isn't a category.
- type: boolean
  name: fdw
  label: fdw
  default: false
  description: Is this a Fokus der Woche article? If yes, <strong>turn on</strong>,
    if no, <strong>keep off</strong>. The default for this is off.
- type: boolean
  name: paid
  label: paid
  description: Is this a paid article? If yes, <strong>turn on</strong>, if no, <strong>keep
    off</strong>. For now there are no paid articles, so the default is off.
  default: false
- name: artikel
  type: boolean
  label: artikel
  default: true
  hidden: true
pages:
- content/20-millionen-baume-als-zeichen-gegen-den-klimawandel.md
- content/26.04.1986-tschernobyl.md
- content/attentat-in-hanau-tragt-die-afd-eine-mitschuld.md
- content/australien-brennt.md
- content/bigfoot-der-menschenaffe-aus-nordamerika.md
- content/billie-eilish-die-angesagteste-pop-sangerin-von-heute.md
- content/boris-johnson-und-sein-brexit.md
- content/corona-halt-die-welt-auf-trab.md
- content/corona-macht-schule.md
- content/corona-und-mein-sackgeld.md
- content/corona-zwischen-demonstrationen-und-maskenpflicht.md
- content/das-fest-der-spende-und-zusammenkunft-in-der-krise.md
- content/das-gute-daran-licht-und-schatten-mit-corona.md
- content/das-kurdische-volk.md
- content/das-perfekte-auto.md
- content/dem-untergang-geweiht-bootsfluchtlinge-auf-dem-weg-nach-europa.md
- content/der-grosse-krieg-ist-nicht-entstanden.was-ist-sonst-geschehen-im-iran.md
- content/die-jagdsaison-warum-5560-hirsche-erschossen-werden.md
- content/die-kurden-in-syrien.md
- content/die-magische-seife.md
- content/die-welt-wartet-sehnlichst-auf-den-impfstoff.md
- content/ein-hoch-auf-das-pflegepersonal.md
- content/es-gab-einmal-die-berliner-mauer.md
- content/fur-kinder-coronazeit-freie-zeit-bleibt-zu-hause.aber-was-tun-gegen-langeweile.md
- content/grossbritannien-und-die-eu-gehen-getrennte-wege.md
- content/heute-corona.vor-100-jahren-spanische-grippe.md
- content/heute-ist-overshoot-day-75-jahre-ende-des-zweiten-weltkriegs-und-welttag-des-roten-kreuzes.md
- content/im-mannerhockey-hat-nun-eine-frau-das-sagen.md
- content/instagram-snapchat-jetzt-ist-tiktok-der-hit.md
- content/keine-corona-infizierten-in-nordkorea.md
- content/kinder-in-not-hier-wird-dir-geholfen.md
- content/kreislaufwirtschaft.md
- content/lesen-oder-gamen.md
- content/nach-dem-brexit-folgte-der-megxit.md
- content/nessie-das-ungeheuer-von-loch-ness.md
- content/pressefreiheit-fur-alle-lander.md
- content/radioaktiver-abfall-vergessen-ist-gefahrlich.md
- content/ruhe-bitte-jetzt-gibt-es-infos.md
- content/schrott-im-weltraum.md
- content/schwul.na-und.md
- content/seit-fast-70-jahren-fliegt-sie-durch-die-lufte.md
- content/sie-sie-sie-auch-me-too.md
- content/spacex-projekt-zwischen-faszination-und-wahnsinn.md
- content/strahlen-tag-und-nacht.md
- content/tiger-king-zwischen-mordern-spinnern-und-wahnsinn.md
- content/treten-sie-ein-gnadige-frau.md
- content/verfolgt-oder-einfach-beschutzt.md
- content/warum-singen-vogel.md
- content/weltmalariatag-im-kampf-gegen-eine-krankheit.md
- content/welttag-der-kulturellen-vielfalt.md
- content/wer-hilft-den-gestrandeten-kindern-von-moria.md
- content/wer-kann-lesen-und-schreiben.md
- content/yeti-der-schneemensch-aus-dem-himalaya.md
