---
label: default-article
hide_body: false
fields:
- type: text
  name: title
  label: Article title
  description: Enter the title of the article here.
- type: text
  name: slug
  label: Article sub-directory
  description: "(ie. https://www.chinderzytig.ch/<strong>the-sub-directory-is-here</strong>).
    Only fill this out if you want a specific sub-directory. If empty, this field
    will automatically take the title with added hypens (-)."
  hidden: true
- type: text
  name: description
  label: description
  description: A one sentence description regarding what the article is about. This
    is use for SEO purposes (ie. when an article is shared or displayed in web search
    results).
- type: datetime
  name: date
  label: Article date and time
  description: The time will only be critical once Chinderzytig is posting numerous
    articles a day.
- type: text
  name: author
  label: Article author
  description: If this field is left blank, "Chinderzytig" will take the place of
    an absent author.
- type: file
  name: hero_img
  label: Main image
  description: This is the main image for the article, which is also displayed on
    the card in the article lists. For this image I suggest you use landscape images
    with a minimum width of 800px. <strong>The larger the image, the better for the
    article.</strong>
- type: text
  name: img_description
  label: Image description
  description: What is the image about (ie. "Refugees standing in food line in Syria").
    This field is important for blind persons using screen readers on our website.
    This description also takes the place of the picture when, for whatever reason,
    the image can't be loaded on the screen.
- type: text
  name: img_photographer
  description: Name of the photographer/artist/creator of the image being used.
  label: Photographer Name
- type: textarea
  name: img_src
  label: Image source
  description: Enter the URL of the website where you sourced the image from.
- name: cc_licence
  type: text
  config:
    required: false
  label: Creative Commons licence type
  description: If Creative Commons attribution is required for the image you are using,
    enter the licence type here, along with the attribution version number if listed
    (ie. CC BY-SA 2.0)<br>You can find a list of the Creative Commons licences <a
    href="https://creativecommons.org/about/cclicenses/" title="" target="_blank">here</a>.
- name: cc_src
  type: text
  config:
    required: false
  description: If Creative Commons attribution is required for the image you are using,
    enter the URL of the webpage citing the specific Creative Commons licence being
    used for the image. You can find a list of the Creative Commons licences <a href="https://creativecommons.org/about/cclicenses/"
    title="" target="_blank">here</a>.
  label: Creative Commons licence reference
- type: list
  name: kategorien
  description: Add any categories that you feel belong to this article. <em>If the
    article you are writing is for Focus der Woche, </em><strong><em>please leave
    this blank!</em></strong>
  config:
    use_select: true
    source:
      type: simple
    options:
    - Nordamerika
    - Südamerika
    - Europa
    - Afrika
    - Asien
    - Antarktis
    - Welt
    - Ozeanien
    - Weltraum Universium
  label: kategorien
- type: list
  name: markierungen
  label: markierungen
  description: Add any tags that you feel belong to this article that are not already
    categories. Standard practice at the moment is to use country names as tags, when
    the article has been assigned to a continent under categories. <em>If the article
    you are writing is for Focus der Woche, </em><strong><em>please leave this blank!</em></strong>
  config:
    use_select: true
    source:
      type: simple
    options:
    - Gesellschaft
    - Gesundheit
    - Kultur
    - Medien
    - Natur
    - Organisationen
    - Personen
    - Politik
    - Sport
    - Wirtschaft
    - Wissenschaft
- name: arbeitsmaterial
  type: text
  config:
    required: false
  label: Arbeitsmaterial
  description: Add the file name (without the extension .pdf) to this field. Be sure
    to add the arbeitsmaterial shortcode to the end of your article.
- type: boolean
  name: fdw
  label: Fokus der Woche article?
  default: false
  description: Is this a Fokus der Woche article? If yes, <br>toggle the switch to
    the right (<strong>it will turn green when on</strong>). <strong>Remember:</strong>
    <em>Fokus der Woche artikels shouldn't have any categories or tags assigned to
    it.</em><br>
- type: boolean
  name: paid
  label: Paid article?
  default: false
  hidden: true
- name: artikel
  type: boolean
  label: artikel
  default: true
  hidden: true
pages:
- content/2-jahre-gelbwestenbewegung.md
- content/20-jahre-tot-noch-immer-unvergessen.md
- content/20-millionen-baume-als-zeichen-gegen-den-klimawandel.md
- content/26.04.1986-tschernobyl.md
- content/9-11-ein-datum-das-die-welt-veranderte.md
- content/Giftige Tiere.md
- content/ab-nach-sudkorea.md
- content/abschied-und-neuanfang-in-amerika.md
- content/abstimmung.md
- content/abstimmungssonntag-spezial-gesichter-enthullen-identitat-im-internet-auch-oko-palm-ol.md
- content/abstimmungswochenende-vaterschaftsurlaub.md
- content/achtsamkeit-die-kunst-an-nichts-zu-denken.md
- content/achtung-fertig-olympia.md
- content/adventszeit-wie-weihnachten-in-anderen-religionen-gefeiert-wird.md
- content/affentheater.md
- content/afghanistan-ein-land-versinkt-im-chaos.md
- content/am-ende-gewinnt-das-gute-eben-doch.md
- content/amerika-hat-gewahlt-joe-biden-wird-neuer-prasident.md
- content/and-now-a-happy-new-year.md
- content/angriff-eines-tigers-wo-liegt-die-schuld.md
- content/april-april.woher-kommst-du-wohl.md
- content/arbeiten-fur-das-wohl-von-anderen.md
- content/atomkraftwerke-und-ihre-folgen.md
- content/attentat-in-hanau-tragt-die-afd-eine-mitschuld.md
- content/auch-das-noch...die-riesenhornisse-kommt.md
- content/aufmerksamkeit-fur-alle-die-sich-nicht-gehor-verschaffen-konnen.md
- content/aus-den-augen-aus-dem-sinn.md
- content/ausnahmezustand-in-der-schweiz.md
- content/australien-brennt.md
- content/benzinknappheit-im-vereinigten-konigreich.md
- content/bestattung-78-000-jahre-alt.md
- content/bienen.md
- content/bigfoot-der-menschenaffe-aus-nordamerika.md
- content/billie-eilish-die-angesagteste-pop-sangerin-von-heute.md
- content/bin-ich-schon-was-ist-schon-like-oder-nicht-like.md
- content/bio-und-fair-trade.md
- content/bitcoin-und-co.md
- content/blutmond.md
- content/boris-johnson-und-sein-brexit.md
- content/bts-3-buchstaben-gehen-um-die-welt.md
- content/chile-das-land-das-am-schnellsten-impft.md
- content/china-an-der-angel.md
- content/corona-halt-die-welt-auf-trab.md
- content/corona-krise-verscharft-ungleichheiten-global-und-nationa.md
- content/corona-macht-schule.md
- content/corona-und-mein-sackgeld.md
- content/corona-verhaltensregeln.md
- content/corona-wie-geht-es-weiter.md
- content/corona-zwischen-demonstrationen-und-maskenpflicht.md
- content/covid-19-im-land-der-kiwis.md
- content/das-covid-zertifikat.md
- content/das-erste-zwischenzeugnis-fur-den-neuen-us-prasidenten-joe-biden.md
- content/das-fest-der-spende-und-zusammenkunft-in-der-krise.md
- content/das-gute-daran-licht-und-schatten-mit-corona.md
- content/das-kurdische-volk.md
- content/das-kurz-e-kanzleramt.md
- content/das-leben-hat-wieder-einen-sinn....md
- content/das-perfekte-auto.md
- content/das-phanomen-black-friday.md
- content/das-privileg-lesen-zu-konnen.md
- content/das-recht-auf-ein-sicheres-leben.md
- content/das-uberleben-der-starksten.md
- content/das-universum-und-wir.md
- content/das-wettrennen-um-die-eiswuste.md
- content/dem-krebs-die-stirn-bieten.md
- content/dem-untergang-geweiht-bootsfluchtlinge-auf-dem-weg-nach-europa.md
- content/demokratie-wenn-mitentscheiden-schwierig-wird.md
- content/dene-wo-s-guet-geit.md
- content/der-beste-freund-des-menschen.md
- content/der-boden-ist-lava.md
- content/der-dreikonigstag-im-wandel.md
- content/der-fall-alexei-nawalny.md
- content/der-grosse-krieg-ist-nicht-entstanden.was-ist-sonst-geschehen-im-iran.md
- content/der-lange-krieg-ums-heilige-land.md
- content/der-libanon-kommt-nicht-zur-ruhe.md
- content/der-nobelpreis-beruhrt.md
- content/der-starke-hurrikan-dorian-zerstort-die-bahamas.md
- content/diagnose-autismus.md
- content/die-antarktis-der-sechste-kontinent.md
- content/die-arbeiterpartei-kurdistan-pkk.md
- content/die-italienische-kuche-mehr-als-genuss.md
- content/die-jagdsaison-warum-5560-hirsche-erschossen-werden.md
- content/die-kurden-in-syrien.md
- content/die-lunge-brennt-immer-noch.md
- content/die-magische-seife.md
- content/die-polizei-dein-freund-und-jerusalema-tanzer.md
- content/die-unendliche-geschichte-corona-immer-wieder.md
- content/die-welt-ist-rund.md
- content/die-welt-wartet-sehnlichst-auf-den-impfstoff.md
- content/die-zwiebeln-sind-los.md
- content/diego-armando-maradona-ein-leben-zwischen-genie-und-wahnsinn.md
- content/digitalisierung-geht-besser-warum-es-ein-nein-zur-e-id-braucht.md
- content/djokovic-down-under.md
- content/donald-trump-spricht.md
- content/ein-blick-zuruck-ins-jahr-2021.md
- content/ein-hoch-auf-das-pflegepersonal.md
- content/ein-hoch-auf-den-drahtesel.md
- content/ein-land-zwei-systeme.md
- content/ein-nationalfeiertag-mit-einem-faden-beigeschmack.md
- content/ein-sommer-ganz-im-zeichen-des-sports.md
- content/ein-wirtschaftsevent-trotz-corona.md
- content/eine-wegweisende-wahl-nicht-nur-fur-deutschland.md
- content/einen-halben-tag-arbeiten-um-ein-blatt-papier-zu-kaufen.md
- content/einfach-ploppen-und-la-bambele.md
- content/es-dreht-sich-der-kreis-beispiel-burma.md
- content/es-gab-einmal-die-berliner-mauer.md
- content/es-lebe-der-sport.md
- content/es-war-einmal-ein-vereinigtes-land.md
- content/eyjafjallajokull-der-vulkanausbruch-der-gegenwart.md
- content/feiertag-protesttag.md
- content/fincen-files-ein-journalistennetzwerk-deckt-auf.md
- content/fokus-der-woche-kommentar-der-redaktion-rassismus-ist-leider-tief-verankert.md
- content/fokus-der-woche-kommentar-der-redaktion-wir-konnen-nicht-atmen.md
- content/fondue-oder-raclette.md
- content/frankreich-und-algerien-eine-schwierige-geschichte.md
- content/freiheit-durch-tod.md
- content/frieden.md
- content/funfzig-jahre-frauenstimmrecht.md
- content/fur-kinder-coronazeit-freie-zeit-bleibt-zu-hause.aber-was-tun-gegen-langeweile.md
- content/ganz-normal-verschieden.md
- content/gewitter-wie-gefahrlich-sind-blitz-und-donner.md
- content/grossbritannien-und-die-eu-gehen-getrennte-wege.md
- content/grundung-nordkoreas.md
- content/halloween-mehr-als-nur-kurbisse-verkleidungen-und-sussigkeiten.md
- content/happy-birthday-wladimir.md
- content/heile-heile-sage-oder-jetzt-wird-geimpft.md
- content/heuschrecken-plagen-ostafrika.md
- content/heute-corona.vor-100-jahren-spanische-grippe.md
- content/heute-ist-der-tag-der-demokratie.md
- content/heute-ist-overshoot-day-75-jahre-ende-des-zweiten-weltkriegs-und-welttag-des-roten-kreuzes.md
- content/hier-ist-der-tod-ein-fest-der-freude.md
- content/holi-der-farbenfrohe-fruhlingsanfang.md
- content/humpahumpatataraa.md
- content/illegal-adoptiert.md
- content/im-kampf-gegen-das-gletscherschmelzen.md
- content/im-mannerhockey-hat-nun-eine-frau-das-sagen.md
- content/im-meer-schwimmen-fische-und-teddybaren.md
- content/im-stadion-mit-erlaubnis-bubele.md
- content/impfparty-impfdorf-impf-talk-gute-ideen-oder-reine-geldverschwendung.md
- content/impfungen-gegen-das-coronavirus.md
- content/instagram-snapchat-jetzt-ist-tiktok-der-hit.md
- content/internationaler-anti-diat-tag.md
- content/internationaler-friedenstag.md
- content/island.md
- content/ja-es-gibt-einen-weihnachtsmann.md
- content/ja-wie-steht-es-denn-nun-um-diesen-weihnachtsmann.md
- content/kasekuchen-ist-nicht-gleich-kasekuchen-uber-unterschiede-im-gebrauch-der-deutschen-standardprache.md
- content/keine-corona-infizierten-in-nordkorea.md
- content/kid-of-the-year.md
- content/kinder-in-not-hier-wird-dir-geholfen.md
- content/klein-klaus-ganz-gross.md
- content/klimaschutz-ade-wie-erklart-man-das-den-kindern.md
- content/komodowarane-ein-wildschwein-zum-fruhstuck.md
- content/konflikt-um-tiktok.md
- content/kreislaufwirtschaft.md
- content/krim-die-kleine-halbinsel-im-grossen-konflikt.md
- content/lasst-uns-ofter-weinen.md
- content/last-christmas.md
- content/leben-auf-dem-aletschgletscher-von-wasserflohen-und-anderen-wesen.md
- content/lesen-oder-gamen.md
- content/marini-maruni-maroni.md
- content/marokko-faszinierendes-land-der-gegensatze.md
- content/maskenpflicht.oder-nicht.md
- content/mein-korper-geht-euch-nichts-an.md
- content/menschen-verhungern-in-afghanistan.md
- content/merci-mueter.md
- content/minen-eine-heimtuckische-waffe.md
- content/mir-ist-es-wohler-so.md
- content/mission-zum-mars-der-lange-weg-zur-neuen-heimat.md
- content/money-money-was-ist-eigentlich-auf-den-schweizer-banknoten-drauf.md
- content/moria-brennt-und-europa-schaut-weg.md
- content/nach-dem-brexit-folgte-der-megxit.md
- content/nelson-mandela-und-sein-kampf-gegen-die-apartheid.md
- content/nessie-das-ungeheuer-von-loch-ness.md
- content/neujahresvorsatze-wieso-es-so-schwer-ist-diese-einzuhalten.md
- content/ni-hao-afrika.md
- content/nicht-impfen-impfen-fur-die-freiheit.md
- content/nordkorea-noch-armer-wegen-corona.md
- content/oh-tannen-baum.md
- content/ostern-mehr-als-der-osterhase-und-eier-suchen.md
- content/palastinensischer-terrorismus.md
- content/personenfreizugigkeit-infiziert-corona-unser-stimmverhalten.md
- content/pressefreiheit-fur-alle-lander.md
- content/proteste-in-kolumbien.md
- content/proteste-in-weissrussland.md
- content/quarantane-nach-den-herbstferien.md
- content/radioaktiver-abfall-vergessen-ist-gefahrlich.md
- content/rassismus-teil-3-die-proud-boys-trumps-schlagertruppe.md
- content/rassismusserie-teil-1-qanon-die-verschworungs-fanatiker-aus-dem-internet.md
- content/rassismusserie-teil-2-der-ku-klux-klan.md
- content/rentiere-die-advents-stars-aus-dem-hohen-norden.md
- content/republikaner-und-demokraten-die-zwei-parteien-der-usa.md
- content/rise-up-for-change-aktionswoche-fur-den-klimaschutz.md
- content/rotes-quecksilber-ein-gefahrliches-gerucht.md
- content/ruhe-bitte-jetzt-gibt-es-infos.md
- content/schon-gepackt-die-reise-der-zugvogel.md
- content/schrott-im-weltraum.md
- content/schwitzen-im-regenwald.md
- content/schwul.na-und.md
- content/seaspiracy-unsere-weltmeere-in-not.md
- content/seit-fast-70-jahren-fliegt-sie-durch-die-lufte.md
- content/sie-helfen-wo-hilfe-am-dringendsten-notig-ist.md
- content/sie-sie-sie-auch-me-too.md
- content/skifahren-corona-in-der-schweiz.md
- content/skifahren-ja-oder-nein.md
- content/spacex-projekt-zwischen-faszination-und-wahnsinn.md
- content/spannung-steigt-wer-wird-neuer-prasident-von-amerika.md
- content/sport-ist-immer-auch-eine-politische-angelegenheit.md
- content/spuckfest-massentest.md
- content/stau-im-suezanal.md
- content/sterne.md
- content/strahlen-tag-und-nacht.md
- content/super-abstimmungswochenende-im-september.md
- content/syrien-von-der-unabhangigkeit-zum-burgerkrieg.md
- content/tag-der-arbeit-worum-geht-es-eigentlich.md
- content/tag-der-erfinder-innen.md
- content/tag-der-jugend-in-indien-national-youth-day.md
- content/tag-der-liebenden-tag-des-geldes.md
- content/tag-des-meeres.md
- content/tauwetter-in-der-antarktis.md
- content/terrorismus-gefurchtet-und-bekampft.md
- content/tiger-king-zwischen-mordern-spinnern-und-wahnsinn.md
- content/toooor-hopp-schwiiz-ab-an-die-wm-im-winter.md
- content/traumberuf-influencer-in.md
- content/treten-sie-ein-gnadige-frau.md
- content/tschuss-winterblues.md
- content/ukraine-und-russland-streit-ohne-ende.md
- content/unerwunschte-krabbeltiere.md
- content/unsere-ladenserie-teil-1-migros.md
- content/unsere-ladenserie-teil-2-coop.md
- content/unsere-ladenserie-teil-3-aldi-und-lidl.md
- content/unsere-ladenserie-teil-4-denner-volg-und-spar.md
- content/us-wahlen-im-herbst.md
- content/vanille-schokolade-oder-doch-lieber-safran-und-truffel-die-geschichte-der-glace.md
- content/veganuary.md
- content/verfolgt-oder-einfach-beschutzt.md
- content/vietnam-ein-krieg-im-krieg-ein-drama-sondergleichen.md
- content/vom-mann-zum-stern-eine-annaherung-ans-gendern.md
- content/von-bis-zu.md
- content/von-dagobert-duck-zu-robin-hood.md
- content/von-koniginnen-und-konigen-in-europa.md
- content/von-liberal-zu-konservativ-supreme-court.md
- content/von-pocken-zu-covid-19-die-entdeckung-und-entwicklung-des-impfstoffs.md
- content/wahlen-in-afrika-aber-haben-die-menschen-wirklich-eine-wahl.md
- content/wann-offnet-australien-wieder.md
- content/warum-singen-vogel.md
- content/warum-stellen-wir-eigentlich-zwei-mal-im-jahr-die-uhren-um.md
- content/warum-treten-die-nicht-endlich-zuruck.md
- content/was-bist-du-fur-ein-sternzeichen.md
- content/was-die-abstimmungsresultate-bedeuten.md
- content/was-ist-los-in-den-schulen-im-hohen-norden.md
- content/was-ist-los-in-venezuela.md
- content/was-machen-fische-im-winter.md
- content/was-macht-eigentlich-der-bundesprasident.md
- content/weihnachten-in-aller-welt.md
- content/weltfrauentag.md
- content/weltgesundheitstag.md
- content/weltknuddeltag-und-keiner-darf-knuddeln.md
- content/weltmalariatag-im-kampf-gegen-eine-krankheit.md
- content/welttag-der-kulturellen-vielfalt.md
- content/weltuntergang-verhindern-oder-doch-lieber-apero.md
- content/wem-gehort-der-weltraum.md
- content/wenn-die-kleinen-ganz-grosses-erreichen.md
- content/wenn-menschen-zur-ware-werden.md
- content/wenn-sich-eine-kleine-bevolkerungsgruppe-gegen-das-parlament-auflehnt.md
- content/wenn-zwei-sich-streiten-freut-sich-der-dritte.md
- content/wer-hilft-den-gestrandeten-kindern-von-moria.md
- content/wer-kann-lesen-und-schreiben.md
- content/wer-liest-eigentlich-meine-chats.md
- content/wir-sind-im-tv.md
- content/woher-der-osterhase-mit-den-schokoeiern-kommt.md
- content/wohin-der-wind-weht.md
- content/wolfe-in-der-schweiz.md
- content/yeti-der-schneemensch-aus-dem-himalaya.md
- content/zappelphilipp-traumerin-krankheit-oder-wesensart.md
- content/zwischen-verantwortung-und-krieg.md
